proceed-file script for .emf files. Config not tested, renorming coefficient unknown

diff --git a/scripts/proceed-file b/scripts/proceed-file
--- a/scripts/proceed-file
+++ b/scripts/proceed-file
@@ -2,53 +2,86 @@
 
 #echo "Usage: proceed-file <dir> <file-without-extension> <format>"
 
+function checkExitCode 
+{
+    if [ "$?" != "0" ];
+    then
+        echo "  ! Stopping."
+        exit
+    fi
+}
+
 dir=$1
 file=$2
 report=Report.fr
 faReport=report.txt
 
+echo "Starting log at `date`." | tee log.log
+
 if [ "$4" == "limits" ];
 then
-	limitsOption="-l $5 $6"
-	echo "  i Enabling option $limitsOption"
+    limitsOption="-l $5 $6"
+    echo "  i Enabling option $limitsOption"
 fi
 
-if [ "$3" == "myza" ];
+if [ "$3" == "dsf" ];
 then 
-	filedsf=$file.dsf
-	filedat=$file.dat
+    filedsf=$file.dsf
+    filedat=$file.dat
 
-	fullname=$dir$filedsf
+    fullname=$dir/$filedsf
 
-	echo "  + Coping $fullname..."
-	cp $fullname .
-	echo "  + Running Faildows tool..."
-	wine dsf2dat.exe $filedsf
+    echo "  + Coping $fullname..." | tee -a log.log
+    cp $fullname .
+    
+    checkExitCode
+    
+    echo "  + Running Faildows tool..." | tee -a log.log
+    wine dsf2dat.exe $filedsf
 
-	echo "  + Creating plain data..."
-	./flux-analysis -f $filedat -F dat -t "DATA-plain.txt" $limitsOption -u 6 -o "DATA.bin" -r -0.005 -K 30 -z +4 >> log.log
+    checkExitCode
+    
+    echo "  + Creating plain data..." | tee log.log
+    ./flux-analysis -f $filedat -F dat -t "DATA-plain.txt" $limitsOption -u 6 -o "DATA.bin" -r -0.005 -K 30 -z +4 | tee -a log.log
 
-	echo "  + Filtering..."
-	./flux-analysis -i DATA.bin -t DATA.txt -n 1.8 2 -S "config-myza.cfg" -s "DATA-strikes.txt" -M "hist.txt" -K 340 -z +4 -R $faReport  $limitsOption >> log.log
+    checkExitCode
+    
+    echo "  + Filtering and detecting..." | tee log.log
+    ./flux-analysis -i DATA.bin -t DATA.txt -n 1.8 2 -S "config-myza.cfg" -s "DATA-strikes.txt" -M "hist.txt" -K 340 -z +4 -R $faReport  $limitsOption | tee -a log.log
 
-	echo "  + Plotting E(t) graph with gnuplot..."
-	cat plot-graph.pattern | sed s/"#FILENAME#"/$file/ | sed s/"#DATETIME#"/$file/ > plot-current.gp
-	gnuplot plot-current.gp >> log.log 2>&1
-
-	echo "  + Plotting histogram with gnuplot..."
-	cat plot-hist.pattern | sed s/"#FILENAME#"/$file/ | sed s/"#DATETIME#"/$file/ > plot-current.gp
-
-	gnuplot plot-current.gp >> log.log 2>&1
-	
-	count=`cat $faReport`
-	if [ "$count" !=  "0" ];
-	then
-		echo "In $file founded: $count" >> Report.fr
-	fi
-	
-elif [ "$3" == "ipf" ];
+    checkExitCode
+    
+elif [ "$3" == "efm" ];
 then
-	echo "hh"
+    fileefm=$file.efm
+
+    fullname=$dir/$fileefm
+
+    echo "  + Coping $fullname..." | tee -a log.log
+    cp $fullname .
+    
+    echo "  + Creating plain data..." | tee log.log
+    ./flux-analysis -f $fileefm -F efm -t "DATA-plain.txt" $limitsOption -o "DATA.bin" -z +4 -K 3
+    
+    echo "  + Filtering and detecting..." | tee log.log
+    ./flux-analysis -i DATA.bin -t DATA.txt -n 1.8 2 -S "config-iapras.cfg" -s "DATA-strikes.txt" -M "hist.txt" -K 340 -z +4 -R $faReport  $limitsOption | tee -a log.log
+    
 else
-	echo "    Invalid file format specified."
+    echo "    Invalid file format specified."
+    exit
+fi
+
+echo "  + Plotting E(t) graph with gnuplot..." | tee -a log.log
+cat plot-graph.pattern | sed s/"#FILENAME#"/$file/ | sed s/"#DATETIME#"/$file/ > plot-current.gp
+gnuplot plot-current.gp >> log.log 2>&1
+
+echo "  + Plotting histogram with gnuplot..." | tee -a log.log
+cat plot-hist.pattern | sed s/"#FILENAME#"/$file/ | sed s/"#DATETIME#"/$file/ > plot-current.gp
+
+gnuplot plot-current.gp 2>&1 | tee -a log.log
+
+count=`cat $faReport`
+if [ "$count" !=  "0" ];
+then
+    echo "In $file founded: $count" >> Report.txt
 fi
